Test_Workspace_Name = "test_workspace_name"
Test_Subscription = "test_subscription"
Test_Resource_Group = "test_resource_group"
Test_Base_Url = "test_base_url"
Default_API_Version = "2020-09-01-preview"
